[package]
name = "utemplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexical = "6.1.1"
utemplate_macro = { version = "0.1.0", path = "../utemplate_macro" }
